# mysql
addr: 127.0.0.1:3306
user: root
pass: 123456

charset: utf8
slave_id: 1001 #slave ID
flavor: mysql

#mongodb
mongodb_host: 127.0.0.1
mongodb_port: 27017
mongodb_username: root
mongodb_password: 123456


rule:
  - schema: school
    table: students 
    target: mongodb 
    order_by_column: id 
    mongodb_database: school
    mongodb_collection: students
    # columns to include
    include_columns: 
      - name
      - age
    # columns to exclude
    exclude_columns: 
      - address
    # column mappings, means rename mobile to phone
    column_mappings: 
      - source: mobile
        target: phone
    # new columns to add
    new_columns: 
      - name: status
        type: string
        templ: true
        value: "{% if is_active %}good{% else %}bad{% endif %}"
    