# mysql配置
addr: 127.0.0.1:3306
user: root
pass: 123456

charset: utf8
slave_id: 1001 #slave ID
flavor: mysql #mysql or mariadb,默认mysql

#mongodb连接配置
mongodb_addrs: 10.136.134.218
mongodb_port: 27017
mongodb_username: root
mongodb_password: 123456

#规则配置
rule:
  - schema: packit
    table: testszeekr_env 
    target: mongodb 
    order_by_column: id 
    mongodb_database: test
    mongodb_collection: test_env
