# mysql
addr: 127.0.0.1:3306
user: root
pass: 123456

charset: utf8
slave_id: 1001 #slave ID
flavor: mysql #mysql or mariadb,默认mysql

#mongodb
mongodb_host: 127.0.0.1
mongodb_port: 27017
mongodb_username: root
mongodb_password: 123456


rule:
  - schema: gitea
    table: students 
    target: mongodb 
    order_by_column: id 
    mongodb_database: test
    mongodb_collection: students
  - schema: gitea
    table: students 
    target: mongodb 
    order_by_column: id 
    mongodb_database: test
    mongodb_collection: company
